- Bonesplitters.cat
- Flesh-eater_Courts.cat
- Splintered_Fang.cat
- Warhammer_Age_of_Sigmar_Warcry.gst
Added Bonesplitters, Flesh-eater Courts, and Splintered Fang.
Adding data for #3
> More factions

- Flesh-eater_Courts.cat
> Crypt Horror removed leader fix

- Legions_of_Nagash.cat
My first go at this, hopefully it's ok
> Legions of nagash

- Bonesplitterz.cat
- Warhammer_Age_of_Sigmar_Warcry.gst
Closes #24 - correct faction name in all locations
> 24-fix-name-bonesplitterz

- Splintered_Fang.cat
D'oh. Forgot to add to root selection. Fixing #31
> Added VB with Barbed Whip to Root Selection

- Kharadron_Overlords.cat
- Stormcast_Warrior_Chamber.cat
I believe this adds the Stormcast Warrior Chamber and Kharadron Overlords as data for the app. This is my first contribution to the project, so forgive me if I've made any serious mistakes. If I need to modify anything, please do tell me!
> Add Stormcast Warrior Chamber and Kharadron

- Ogor_Mawtribes.cat
> Ogor fixes to points and leadbelcher weapon profile

- Blades_of_Khorne_Bloodbound.cat
- Blades_of_Khorne_Daemons.cat
- Hedonites_of_Slaanesh.cat
- Maggotkin_of_Nurgle_Daemons.cat
- Maggotkin_of_Nurgle_Rotbringers.cat
- Seraphon.cat
- Stormcast_Sacrosanct_Chamber.cat
- Sylvaneth.cat
- Warhammer_Age_of_Sigmar_Warcry.gst
Catalogues added, added all abilities but missing data that's covered up in preview, and fighters guessed based on number of profiles in description for some factions.
> Wave 3 Factions

- Sylvaneth.cat
Still needs abilities finished
> Added Profiles

- Slaves_to_Darkness.cat
> Fixed StD Abilities

- Beasts_of_Chaos.cat
> Fixes Missing Default Costs

- Maggotkin_of_Nurgle_Daemons.cat
- Maggotkin_of_Nurgle_Rotbringers.cat
> Nurgle Daemons and Rotbringers added

- Disciples_of_Tzeentch_Daemons.cat
> Flamers points fix

- Disciples_of_Tzeentch_Arcanites.cat
- Slaves_to_Darkness.cat
> Fixes to #92 and #93

- Warhammer_Age_of_Sigmar_Warcry.gst
> Beasts allies

- The_Unmade.cat
Hi 👋 ,
Thanks for the app and the data. Creating my unmade war-band I found a small typo. Here the fix :)
Happy wargaming! 🤘
> Fix typo: "nunber" changed to number

- Order-StormcastEternal-VanguardChamber.cat
> Raptor Points Fix and Added Default Profile

- Chaos-ScionsOfTheFlame.cat
> fixed cost

- Chaos-SpireTyrants.cat
- Death-LegionsOfNagash.cat
> Fixes for missing Headclaimer and broken link in LoN

- Chaos-CorvusCabal.cat
> Fixes duplicate cost

- Destruction-OgorMawtribes-LeadersAbilities.cat
> fixed typo on thunderfist

- Death-LegionsOfNagash.cat
> fixed missing thrall and monsters

- Chaos-SlavesToDarkness-LeadersAbilities.cat
> Fixed Exalted mixup and missing unit

- Order-KhainiteShadowstalkers.cat
> Added missing Darkflame profile
